### ISSUE TITLE
Cleaning up branches

### ISSUE THREAD

**Issue by YairSlobodin1** [np-guard/vpc-network-config-synthesis#169]
Can I delete the `toml`, `hcl`, `optimize-redundant` and `hclio` branches? @elazarg

**Comment by elazarg** [comment]
Yes

**Comment by elazarg** [comment]
We can perhaps add a link to them here in a closed issue, in case at some point hcl input would be of interest.

**Comment by YairSlobodin1** [comment]
[hclio](https://github.com/np-guard/vpc-network-config-synthesis/tree/hclio)
[hcl](https://github.com/np-guard/vpc-network-config-synthesis/tree/hcl)
[optimize-redundant](https://github.com/np-guard/vpc-network-config-synthesis/tree/optimize-redundant)
[toml](https://github.com/np-guard/vpc-network-config-synthesis/tree/toml)
