### ISSUE TITLE
Support subnets, CIDRs, segments in SG generation

### ISSUE THREAD

**Issue by zivnevo** [np-guard/vpc-network-config-synthesis#174]

**Comment by YairSlobodin1** [comment]
@zivnevo do you mean segments of instances/nifs?

**Comment by zivnevo** [comment]
I'm not quite sure what we meant here. Are segments of other types (subnets, cidrs) supported in SG synthesis?

**Comment by kyorav** [comment]
I have no idea how to prioritize.
Note that we chose the word "segment" because it was meant for subnets and cidrs. Sets of instances and NIFs would not be called segments, but I guess they could be useful all the same...?
