### ISSUE TITLE
Usability using generated terraform code

### ISSUE THREAD

**Issue by kyorav** [np-guard/vpc-network-config-synthesis#68]
The way we generate SGs and nACLs currently means that users need to figure out which ACL/SG goes where based on the _terraform name_ of the ACL/SG matching the _resource name_ they need to be attached to. We need to explore a better way, probably by generating local variables for mappings or something.

**Comment by kyorav** [comment]
this is not urgent, postponed until we get to the usability improvement stage.

**Comment by YairSlobodin1** [comment]
Solved by other issues.
